<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_All Rejected Leave</name>
   <tag></tag>
   <elementGuidId>7c7161fd-0a1a-4dc5-8907-395afcb19ef5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='virtualAutocompleteListbox_554c8b0c0e4af']/li[3]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;All Rejected Leave&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0578ef33-0ccc-4d6d-bcb8-914fd2ad5c44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> virtualAutocompleteOptionText</value>
      <webElementGuid>54c2bf57-06c8-465a-847d-97e765bbeade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>1110:0</value>
      <webElementGuid>db871119-2ea3-46ad-9ed5-e9157bba4932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All Rejected Leave</value>
      <webElementGuid>d7149730-b16f-4af0-bf50-310b4cf5ad33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;virtualAutocompleteListbox_554c8b0c0e4af&quot;)/li[@class=&quot;slds-dropdown__item has-icon--left   forceVirtualAutocompleteMenuOption&quot;]/a[1]/span[@class=&quot;virtualAutocompleteOptionText&quot;]</value>
      <webElementGuid>00f5cccc-62ff-453c-932c-86d2e60325a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='virtualAutocompleteListbox_554c8b0c0e4af']/li[3]/a/span</value>
      <webElementGuid>a02f111b-1eaf-4d25-8772-1fb0df99899b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selected'])[2]/following::span[1]</value>
      <webElementGuid>5a6add87-be9d-48e5-b98a-a7acf60917dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[1]/following::span[3]</value>
      <webElementGuid>e406395f-18a6-4f7c-9f46-73880581adc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selected'])[3]/preceding::span[1]</value>
      <webElementGuid>bcad8c91-6186-42d5-afab-31995447f45f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Applied Leave'])[2]/preceding::span[3]</value>
      <webElementGuid>b5100e85-6d16-4dc0-930e-f181a6449999</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='All Rejected Leave']/parent::*</value>
      <webElementGuid>03cf6f75-c128-4623-99da-793640e30569</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/span</value>
      <webElementGuid>28bbf3e7-7b39-456d-9620-226e334b802c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'All Rejected Leave' or . = 'All Rejected Leave')]</value>
      <webElementGuid>2665dd15-7844-4c44-943c-ec7579bbb988</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
