<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Recently Viewed</name>
   <tag></tag>
   <elementGuidId>084bdbcd-5239-4957-910f-f42f04b7261a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#virtualAutoCompleteMenuOption_5a42783cc4a6d > span.virtualAutocompleteOptionText</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='virtualAutoCompleteMenuOption_5a42783cc4a6d']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Selected Recently Viewed&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>61a4e22a-e6ae-453f-9036-19a5cb360036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> virtualAutocompleteOptionText</value>
      <webElementGuid>5b857d23-2ee6-41b5-83a1-c9b4cc40c69c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>2083:0</value>
      <webElementGuid>a1511b8e-02c6-4902-8a5f-5b639eca4a7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Recently Viewed</value>
      <webElementGuid>f7bb5bc0-609a-4760-a5ce-0246474b95e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;virtualAutoCompleteMenuOption_5a42783cc4a6d&quot;)/span[@class=&quot;virtualAutocompleteOptionText&quot;]</value>
      <webElementGuid>2c935712-9c06-4dbf-a0f1-55d24f017f16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='virtualAutoCompleteMenuOption_5a42783cc4a6d']/span</value>
      <webElementGuid>7be0b535-7333-4a26-896d-db4bc1e17258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selected'])[7]/following::span[1]</value>
      <webElementGuid>06c7fffa-2630-4b06-ad5d-5f76cafaf314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pending Approvals'])[1]/following::span[3]</value>
      <webElementGuid>d17ae6f6-1f53-483e-b495-26f1f06bee2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No results found.'])[1]/preceding::span[2]</value>
      <webElementGuid>346a1d66-4b7b-48d0-bb76-9b90794587f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[3]/preceding::span[2]</value>
      <webElementGuid>d25a03d6-5e02-41d0-88ba-e15f5f667e8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/a/span</value>
      <webElementGuid>37c13fee-4176-4640-9906-1bbd5680f154</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Recently Viewed' or . = 'Recently Viewed')]</value>
      <webElementGuid>01f07e6f-fa44-4614-8e15-f1cc57216130</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
