<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_All Leave</name>
   <tag></tag>
   <elementGuidId>c3b317ca-1b27-4c19-9e25-8a3d6eb39ccf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=menuitem[name=&quot;All Leave&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>51171846-3f0f-45dd-a0b3-66c0c17f8425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>1106950d-6df3-44eb-8129-2eb9db928014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>a00a7897-233d-4fd0-b9ab-f3f381fd60a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/CRMITCommunity/s/employee-leave/Employee_Leave__c/00B1K00000ANF4IUAX</value>
      <webElementGuid>7074b545-5271-4d58-aec5-0b8017b68b97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>comm-navigation__top-level-item-link js-top-level-menu-item linkBtn</value>
      <webElementGuid>aa8b87b6-83ec-48ba-9ad4-6d36f8b2e5a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>30:137;a</value>
      <webElementGuid>daba1b1e-6c42-49e4-b09d-852131e7d680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All Leave</value>
      <webElementGuid>39b7399f-a29c-4369-bb96-63990491a6c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;5&quot;)</value>
      <webElementGuid>b2e13e80-aef5-48cd-95bd-d9d7e32b7ff2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='5']</value>
      <webElementGuid>545c606e-9315-4fdc-805b-0931ff0ee24d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='commThemeNav']/div/div/nav/ul/li[6]/a</value>
      <webElementGuid>b3e644de-58c4-4652-a6ee-92cc88779bc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'All Leave')]</value>
      <webElementGuid>3ba3cf62-6b5d-4439-b68b-c4e3fe2b009c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Leave'])[1]/following::a[1]</value>
      <webElementGuid>58cb3f15-5a00-4b8d-9c1a-4cde8a7023c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Attendance Records'])[1]/following::a[2]</value>
      <webElementGuid>e59aa1d6-2628-4788-98b9-8ade9c9dd680</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Engagements'])[1]/preceding::a[1]</value>
      <webElementGuid>64e59110-c285-42a1-90ea-9557514c937e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Team Allocations'])[1]/preceding::a[2]</value>
      <webElementGuid>fa7f027c-e334-4ced-a80e-a868104dfcac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='All Leave']/parent::*</value>
      <webElementGuid>5d5c85fe-be63-48f3-bad3-eab2856bee6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/CRMITCommunity/s/employee-leave/Employee_Leave__c/00B1K00000ANF4IUAX')]</value>
      <webElementGuid>7b0996a4-1e87-444b-8f8f-5ef2e752348a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a</value>
      <webElementGuid>0d04fbf1-2b08-404e-b3a6-0a709f2ecbeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = '5' and @href = '/CRMITCommunity/s/employee-leave/Employee_Leave__c/00B1K00000ANF4IUAX' and (text() = 'All Leave' or . = 'All Leave')]</value>
      <webElementGuid>ca509c4a-e2a0-4a6a-b088-bff5d95af049</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
