<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_All Leave</name>
   <tag></tag>
   <elementGuidId>c6a0109f-52e2-413f-b4b8-7d87ed33ae86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#10</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='10']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=menuitem[name=&quot;All Leave&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>83282eb4-f61b-4479-ba0d-a9ebf77adceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>66ae542a-941f-4c37-8cb3-4a8a3ebef28b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>7cd65d20-0c34-4c42-95b6-132175db4ef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/CRMITCommunity/s/employee-leave/Employee_Leave__c/00B1K00000ANF4IUAX</value>
      <webElementGuid>f51d87c5-41a2-4020-9173-fa3281b1b415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>comm-navigation__top-level-item-link js-top-level-menu-item linkBtn</value>
      <webElementGuid>6237e4a6-16cc-4a0d-9627-3109b0890601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>55:137;a</value>
      <webElementGuid>3a70d279-5894-4aac-9e9c-0aa4e3191e64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All Leave</value>
      <webElementGuid>96ca885f-ea6c-4799-af3f-d44a90dfa5eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;10&quot;)</value>
      <webElementGuid>22669444-332b-43c3-be9c-084a433d2097</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='10']</value>
      <webElementGuid>f551bbb3-13ec-4451-88fd-92167f56c326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='commThemeNav']/div/div/nav/ul/li[11]/a</value>
      <webElementGuid>ad79bef7-6785-4d7e-af6f-36f3a1e833ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'All Leave')]</value>
      <webElementGuid>2ac426bc-8502-4ef9-864a-63bd2b4a6f4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Leave'])[1]/following::a[1]</value>
      <webElementGuid>c041904b-d6ca-4084-86fd-d1cd9f1025ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Attendance Records'])[1]/following::a[2]</value>
      <webElementGuid>0e465454-8269-41bf-ae20-42b72e0a5abf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pit Stop'])[1]/preceding::a[1]</value>
      <webElementGuid>f54f9c92-36d0-4b1c-a694-888927763acf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reports'])[1]/preceding::a[2]</value>
      <webElementGuid>9deeca4a-2ecf-4f4a-9252-43d6c1a48860</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='All Leave']/parent::*</value>
      <webElementGuid>67c9547a-aad2-4c3f-98c7-7ebdab93e495</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/CRMITCommunity/s/employee-leave/Employee_Leave__c/00B1K00000ANF4IUAX')]</value>
      <webElementGuid>dea0ac08-bb8f-4bc7-9acc-44fda147dd95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[11]/a</value>
      <webElementGuid>56e87fb7-cc0a-4d82-b975-b2482a7663f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = '10' and @href = '/CRMITCommunity/s/employee-leave/Employee_Leave__c/00B1K00000ANF4IUAX' and (text() = 'All Leave' or . = 'All Leave')]</value>
      <webElementGuid>1eac4cae-e351-4bcc-9c39-2fbb55179fed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
