<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__End Date</name>
   <tag></tag>
   <elementGuidId>ddb0c4d7-5da0-4523-bab5-ca22439108c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-90</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-90']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;*End Date&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>41eb92a5-9aea-49b3-b6e1-f50999217644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>e0dcedde-cca6-4c21-9f40-1db3dc76ac6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3cf62590-d0b1-4fa5-9d3a-d682c44fc9ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-90</value>
      <webElementGuid>0ac594a3-707e-4258-b46b-4706e6073151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a2280f1a-1dd9-49f1-9d17-f7658e42b27c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>End Date</value>
      <webElementGuid>4abae5f4-f4f5-4621-8aa2-819c9f2d5036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f21c494a-6524-4394-a046-35421e0a0f44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>fmt-text-90</value>
      <webElementGuid>4120c8ae-01a6-4588-ae04-1e667351983e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-90&quot;)</value>
      <webElementGuid>88705d64-fec0-43a2-a454-8fb36cd02467</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-90']</value>
      <webElementGuid>6e1fae63-07c2-450f-8b56-4e8b7e8578c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//lightning-input[@id='end-date-77']/lightning-datepicker/div/div/input</value>
      <webElementGuid>c40eff05-e79a-4c65-8f90-b7db4f9c2344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/lightning-input/lightning-datepicker/div/div/input</value>
      <webElementGuid>ba3cd589-db9d-4453-91f7-10741d4c77c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-90' and @name = 'End Date']</value>
      <webElementGuid>7bfa9c19-41c0-4af2-8674-941f8b669df2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
